# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ming\Desktop\2021_Lin_course\Class2021_ImageProcess_FinalProject\HW2_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fpath_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fpath_btn.setGeometry(QtCore.QRect(80, 60, 151, 41))
        self.fpath_btn.setObjectName("fpath_btn")
        self.stage1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stage1_btn.setGeometry(QtCore.QRect(280, 60, 151, 41))
        self.stage1_btn.setObjectName("stage1_btn")
        self.stage2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stage2_btn.setGeometry(QtCore.QRect(480, 60, 151, 41))
        self.stage2_btn.setObjectName("stage2_btn")
        self.img_ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.img_ScrollBar.setGeometry(QtCore.QRect(80, 620, 551, 16))
        self.img_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.img_ScrollBar.setObjectName("img_ScrollBar")
        self.label_original_img = QtWidgets.QLabel(self.centralwidget)
        self.label_original_img.setGeometry(QtCore.QRect(80, 130, 291, 281))
        self.label_original_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_original_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_original_img.setObjectName("label_original_img")
        self.label_detected_img = QtWidgets.QLabel(self.centralwidget)
        self.label_detected_img.setGeometry(QtCore.QRect(370, 130, 291, 281))
        self.label_detected_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_detected_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_detected_img.setObjectName("label_detected_img")
        self.label_ScrollBar = QtWidgets.QLabel(self.centralwidget)
        self.label_ScrollBar.setGeometry(QtCore.QRect(660, 620, 71, 16))
        self.label_ScrollBar.setObjectName("label_ScrollBar")
        self.label_classifier_img = QtWidgets.QLabel(self.centralwidget)
        self.label_classifier_img.setGeometry(QtCore.QRect(130, 430, 191, 161))
        self.label_classifier_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_classifier_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_classifier_img.setObjectName("label_classifier_img")
        self.label_frac_img = QtWidgets.QLabel(self.centralwidget)
        self.label_frac_img.setGeometry(QtCore.QRect(420, 430, 191, 161))
        self.label_frac_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_frac_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frac_img.setObjectName("label_frac_img")
        self.label_Show_acc = QtWidgets.QLabel(self.centralwidget)
        self.label_Show_acc.setGeometry(QtCore.QRect(710, 130, 161, 281))
        self.label_Show_acc.setObjectName("label_Show_acc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fpath_btn.setText(_translate("MainWindow", "Select Image Floder"))
        self.stage1_btn.setText(_translate("MainWindow", "Detect Scaphoid"))
        self.stage2_btn.setText(_translate("MainWindow", "Classify and Detect Fracture"))
        self.label_original_img.setText(_translate("MainWindow", "Original Image"))
        self.label_detected_img.setText(_translate("MainWindow", "Predicted Image"))
        self.label_ScrollBar.setText(_translate("MainWindow", "TextLabel"))
        self.label_classifier_img.setText(_translate("MainWindow", "Cliped Image"))
        self.label_frac_img.setText(_translate("MainWindow", "Fracture Detect Image"))
        self.label_Show_acc.setText(_translate("MainWindow", "Acc Result Display"))
